pipeline {
    agent any
    environment {
        registry = "841014/python-flask-apps"  // Docker Hub image repository
        registryCredential = 'dockerhub'       // Docker Hub credentials ID in Jenkins
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', credentialsId: 'd66428ce-7861-4620-9473-34067e1e87d0', url: 'https://github.com/dg-satpute/docker-projects-repo.git'
            }
        }
        stage("Build Image") {
            steps {
                script {
                    img = "${registry}:${env.BUILD_ID}"
                    println("Building Docker Image: ${img}")
                    dockerImage = docker.build("${img}")
                }
            }
        }
    }

}