pipeline {
    agent any
    environment {
        DOCKER_IMAGE = <ecr_url>
        AWS_REGION = "ap-south-1"
        EKS_CLUSTER = "sample-eks-cluster"
    }

    stages {
        stage("Checkout") {
            steps {
                git "<git-hub-url>"
            }
        }
        stage("Build Image") {
            steps {
                docker.build("${DOCKER_IMAGE}")
            }
        }
    }

}